# Generated by Django 5.1.3 on 2024-11-15 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
        ('quotes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='awards',
            field=models.ManyToManyField(related_name='users', to='awards.award'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='quotes',
            field=models.ManyToManyField(related_name='users', to='quotes.quote'),
        ),
    ]
