# Generated by Django 5.1.3 on 2024-11-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habit_helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_Habit_Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateTimeField(auto_now_add=True)),
                ('habit_helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_habits', to='habit_helpers.habit_helper')),
            ],
        ),
    ]
