# Generated by Django 5.1.3 on 2024-11-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='started',
            field=models.DateTimeField(),
        ),
    ]
