# Generated by Django 5.1.3 on 2025-07-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_remove_journal_quote_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='entry_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
