# Generated by Django 5.1.3 on 2024-11-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_set', models.CharField(max_length=50)),
                ('quote', models.TextField(max_length=400)),
                ('author', models.TextField(max_length=50)),
            ],
        ),
    ]
