# Generated by Django 5.1.3 on 2024-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_set',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
